description: Server error
content:
  application/json:
    schema:
      $ref: '../schemas/ApiError.yaml'
    example:
      error: ServerError
      message: Something went wrong. {error}
      code: 400